//@version=1
study(title="Fibonaci S/R Channels", shorttitle="Fib SRC", overlay=true)

sensibility = input(13, minval=1)
unicornLines = input(34)
lead = input(13)

linecolor = black

atr= atr(26)

lower0 = lowest(close, sensibility) - (highest(close, sensibility)-lowest(close, sensibility))*0.382 - atr
upper0 = highest(close, sensibility) + (highest(close, sensibility)-lowest(close, sensibility))*0.382 + atr

lower1 = lowest(close, sensibility) - (highest(close, sensibility)-lowest(close, sensibility))*0.618 -atr
upper1 = highest(close, sensibility) + (highest(close, sensibility)-lowest(close, sensibility))*0.618 +atr


lower4 = lowest(close, sensibility) - (highest(close, sensibility)-lowest(close, sensibility))*1.618 -atr
upper4 = highest(close, sensibility) + (highest(close, sensibility)-lowest(close, sensibility))*1.618 +atr

lower5 = lowest(close, sensibility) - (highest(close, sensibility)-lowest(close, sensibility))*2.618 - atr
upper5 = highest(close, sensibility) + (highest(close, sensibility)-lowest(close, sensibility))*2.618 + atr


lowerEMA0 = ema(lower0,unicornLines)
upperEMA0 = ema(upper0,unicornLines)

lowerEMA1 = ema(lower1,unicornLines)
upperEMA1 = ema(upper1,unicornLines)

lowerEMA4 = ema(lower4,unicornLines)
upperEMA4 = ema(upper4,unicornLines)

lowerEMA5 = ema(lower5,unicornLines)
upperEMA5 = ema(upper5,unicornLines)



basis = avg(lowerEMA4, upperEMA4)

plot(basis, offset = lead, color=white)


lEMA0 = plot(lowerEMA0, offset = lead, color=linecolor)
uEMA0 = plot(upperEMA0, offset = lead, color=linecolor)
lEMA1 = plot(lowerEMA1, offset = lead, color=linecolor)
uEMA1 = plot(upperEMA1, offset = lead, color=linecolor)
lEMA4 = plot(lowerEMA4, offset = lead, color=linecolor)
uEMA4 = plot(upperEMA4, offset = lead, color=linecolor)
lEMA5 = plot(lowerEMA5, offset = lead, color=linecolor)
uEMA5 = plot(upperEMA5, offset = lead, color=linecolor)


fill(lEMA0, uEMA0, color=yellow)

fill(lEMA1, lEMA0, color=black)
fill(lEMA5, lEMA4, color=green)

fill(uEMA0, uEMA1, color=black)
fill(uEMA4, uEMA5, color=red)
